### ISSUE TITLE
Show NWC wallet_pubkey (Wallet Nostr public key)

### ISSUE THREAD

**Issue by bumi** [getAlby/nostr-wallet-connect-next#107]
We need some section where we can show details like the wallet pubkey to the user. 

+ wallet pubkey
+ relay / relay connection status

**Comment by verbiricha** [comment]
Do you publish a kind 0 for Alby's wallet pubkey? I couldn't find it. It'd be useful for apps that implement NWC to show some metadata about the connected wallet (basically name and icon/image) when `get_info` metadata is not available. Also useful if an app handles multiple NWC connections and wants to show some information about underlying wallet.

**Comment by rolznz** [comment]
I don't think we do, and we will be incentivizing each user to run their own NWC instance rather than using Alby's one.

It would be nice to have an identifier - but currently we could use `get_info` when connected to get the node alias in that case, since each NWC instance should have its own node alias.

**Comment by rolznz** [comment]
Partially fixed in https://github.com/getAlby/nostr-wallet-connect-next/issues/140
